### PR TITLE
Fix teleportation enchant teleporting when interacting with a block

### PR DESCRIPTION
**Pull request by glisco03**
Moved callback to mixin where actionresult for blockinteract is already known

### CODE REVIEW

**Comment by noeppi-noeppi** [comment]
Could you explain why this is required? I think mixin should be avoided wherever possible (If you're not developing for fabric)

**Comment by glisco03** [comment]
The `PlayerInteractEvent.RightClickBlock` event is fired *before* the block is actually interacted with. This means that you cannot prevent teleporting when, say, clicking a chest which is really annoying. There might be an event for this that I dont know of, but for my purposes the mixin is easier to do. I inject into ItemStack after the actual interaction to make sure it resulted in `ActionResultType.PASS`. This should be very compatible and I don't see any reason to not use a mixin here

**Comment by noeppi-noeppi** [comment]
Ok I'll take a look at it. If there's no other way I'll probably let LibX fire an event. I'll leave this open for now as a remainder for me to fix this.

**Comment by noeppi-noeppi** [comment]
Could you test with the latest commit if the problem you're trying to fix still persists? Sorry that It took me that long to take a look at this.

**Comment by noeppi-noeppi** [comment]
The automatic close was not intended

**Comment by glisco03** [comment]
I haven't had the opportunity to test this yet, and probably won't get it for a few days, but just from looking at the code I'm pretty sure this won't fix the problem. This is because the issues is rooted in the fact that the event is fired before the actual interaction is executed, meaning that whether that original interaction will succeed after the event is unknowable. The only way to solve this, I'm almost certain, is to simulate the interaction, which AFAIK is not possible, or move the callback to after the interaction has occured to gain knowledge about the returned `ActionResultType`

**Comment by noeppi-noeppi** [comment]
Yeah but i think by setting block to default it'll firs try the block interaction and by setting the item result to success it'll then afterwards always fire the item event. If I understood your problem correct, it is fixed. That's why I asked you to test it.

**Comment by glisco03** [comment]
Ok, so it turns out you did fix it, but not by virtue of seeing the block use type. The entire event is not needed, because the item event is obviously fired anyways if the block interaction failed. I suggest just removing the event entirely. 

I didn't previously think of this because I suspected forge would intentionally separate these events.

**Comment by noeppi-noeppi** [comment]
I think there was a reason for it but if it works without, I'll remove it. So the pull request can now be closed I think

**Comment by glisco03** [comment]
Something else I discovered is that newest source seems to always teleport me *into* the anchoe, but I don't know if and how that's related

**Comment by noeppi-noeppi** [comment]
That's because of an issue i "fixed" but thank you for reporting

**Comment by glisco03** [comment]
Ah, I figured out what the event was for. When standing on an anchor and clicking a block no event gets fired, because it counts as block click. To me this means that the check for an empty item was not working, as I see that's also what the event was originally trying to adress

**Comment by glisco03** [comment]
Oh wait maybe I should specify. When standing on an anchor and clicking with an *empty hand*

**Comment by noeppi-noeppi** [comment]
Ok I'll close this now and add an event to libx soon (via mixin) for right clicks with empty hand after the block was handled. Because then I can reuse it when required.

**Pull request closed without merging**
